#!/usr/bin/env bash
# ----------------------------------------------------------------------------
# Generate the iOS platform project for TYC Partner and wire up config.
#
# The repo intentionally ships without an ios/ folder so it is generated by
# YOUR local Flutter version (most reliable path for a real device / TestFlight
# build). Run this once on your Mac, from the repo root:
#
#     bash tool/setup_ios.sh
#
# It is safe to re-run: `flutter create` never clobbers lib/, pubspec.yaml,
# or your .env.
# ----------------------------------------------------------------------------
set -euo pipefail

BUNDLE_ID="com.tradeyourclubs.partner"
DISPLAY_NAME="TYC Partner"

if ! command -v flutter >/dev/null 2>&1; then
  echo "error: flutter not found on PATH. Install Flutter (stable) first." >&2
  exit 1
fi

echo "==> flutter pub get"
flutter pub get

echo "==> Generating iOS platform files (org com.tradeyourclubs)"
flutter create --platforms=ios --org com.tradeyourclubs --project-name tyc_partner .

PBX="ios/Runner.xcodeproj/project.pbxproj"
PLIST="ios/Runner/Info.plist"

echo "==> Setting bundle identifier -> ${BUNDLE_ID}"
# flutter create derives com.tradeyourclubs.tycPartner from org+name; force the
# exact bundle id the App Store record uses.
/usr/bin/sed -i '' -E \
  "s/PRODUCT_BUNDLE_IDENTIFIER = [^;]+;/PRODUCT_BUNDLE_IDENTIFIER = ${BUNDLE_ID};/g" \
  "$PBX"

echo "==> Setting display name -> ${DISPLAY_NAME}"
/usr/bin/plutil -replace CFBundleDisplayName -string "${DISPLAY_NAME}" "$PLIST"
/usr/bin/plutil -replace CFBundleName -string "tyc_partner" "$PLIST" || true

echo "==> Adding camera / photo-library usage descriptions (required by image_picker)"
/usr/bin/plutil -replace NSCameraUsageDescription \
  -string "Take photos of trade-in clubs to attach to the intake record." "$PLIST"
/usr/bin/plutil -replace NSPhotoLibraryUsageDescription \
  -string "Attach existing photos of trade-in clubs to the intake record." "$PLIST"

echo "==> Installing CocoaPods dependencies"
( cd ios && pod install )

cat <<'NEXT'

Done. Next:
  1. Confirm .env exists at the repo root (copy from .env.example if not).
  2. Open ios/Runner.xcworkspace in Xcode.
  3. Select the Runner target -> Signing & Capabilities -> pick your Team.
  4. Verify Bundle Identifier is com.tradeyourclubs.partner.
  5. Run on a device:  flutter run
  6. Archive for TestFlight:  Xcode -> Product -> Archive.

Note: the sed/plutil steps above use BSD (macOS) syntax. On Linux they won't
apply, but the iOS build only happens on macOS anyway.
NEXT
